<?php
	session_start();
	if(isset($_SESSION['user']))
	{
		setcookie('user[0]','',time()-3600,'/');
		setcookie('user[1]','',time()-3600,'/');
		session_unset();
	}
	session_destroy();
	header('location:login.php');
?>